# Generated by Django 2.2.24 on 2021-08-20 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210820_1607'),
        ('home', '0003_workout_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='trainer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workouts_trainer', to='users.Trainer'),
        ),
    ]
